name: Generate PDF with Typst

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Typst to PDF
        uses: typst/compile-typst-action@v1
        with:
          source_path: "src/docs/resume.typ" # Your main Typst file
          output_path: "public/resume.pdf" # Desired output PDF filename
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: typst-pdf
          path: resume.pdf
